### ISSUE TITLE
How do I point to a schema stored locally in the project?

### ISSUE THREAD

**Issue by SyntaxColoring** [sublimelsp/LSP-json#148]
I want a file to be checked with a schema that's stored locally in the project.

I tried this:

```json
"userSchemas": [
	{
		"fileMatch": ["path/to/files/*.json"],
		"uri": "./project_relative/path/to/schema.json"
	}
]
```

But this gives me an error `unable to load schema from '/./project_relative/path/to/schema.json`'`.

I also tried this:

```json
"userSchemas": [
	{
		"fileMatch": ["path/to/files/*.json"],
		"uri": "$project_path/project_relative/path/to/schema.json"
	}
]
```

But it doesn't look like `$project_path` gets expanded. This gives me an error `unable to load schema from '/$project_path/project_relative/path/to/schema.json`'`.

Is this possible?

**Comment by rchl** [comment]
If it's an option to modify the JSON file then those can include a `$schema` property that points to a schema.
