### ISSUE TITLE
LSP-json server unable to start correctly. Spawns a ton of processes, using 90% of ram.

### ISSUE THREAD

**Issue by 7f0c** [sublimelsp/LSP-json#168]
I just figured out why my laptop's fans suddenly goes overdrive. It's because of this extension. I've had this happen many times from the past few week. 

It spawns a ton of node.exe processes and it eats up 90% of my ram. I have to close and reopen sublime text to fix it. Happens almost every day and even multiple times a day. Not quite sure what triggers it.

![Screenshot (568)](https://github.com/sublimelsp/LSP-json/assets/130174233/8843491a-4c8d-4f95-bf75-0141dc2a995a)

**Comment by rwols** [comment]
Are there any hints the sublime console? You can click on View > Show Console in the top menu bar to view the console.

**Comment by rchl** [comment]
This server starts once per ST window (AFAIR). Feels like somehow you trigger a situation where there is tons of windows with JSON files open.

Not sure if ST console would show anything useful in this case but you can also have a look at LSP Log Panel.

**Comment by rchl** [comment]
Closing due to no response.
