### ISSUE TITLE
macOS High Sierra: Failed resolving Node.js Runtime

### ISSUE THREAD

**Issue by jirpok** [sublimelsp/LSP-json#183]
I'm having this issue on macOS High Sierra 10.13.6 and Sublime Text build 4169:

```
Failed to start LSP-json - disabling for this window for the duration of the current session.
Re-enable by running "LSP: Enable Language Server In Project" from the Command Palette.

--- Error: ---
Failed resolving Node.js Runtime. Please check in the console for more details.
```

- No `nvm`,
- node 17.9.1 is in `/usr/local/bin/`, which is in `PATH`,
- `/usr/local/bin/` is included when I run `import os; os.environ["PATH"]` from ST console,
- I use `zsh`.

I had this exact issue on Linux the other day, but it offered to install a new node instance (which really sucks in its own way, sorry, I had to) and that fixed it. That is not the case now, it just throws the message at me.

[This](https://github.com/sublimelsp/LSP/issues/1671) and [this](https://lsp.sublimetext.io/troubleshooting/#updating-the-path-used-by-lsp-servers) didn't help at all. Any ideas?

**Comment by rchl** [comment]
There should be more relevant info in the console (before this message, I guess).

**Comment by jirpok** [comment]
Damn! You're right. I didn't scroll all the way up. It requires node >= 18. Thanks!
