### ISSUE TITLE
Is there an easy way to allow comments in all json files or allow comments for certain file masks?

### ISSUE THREAD

**Issue by ardabro** [sublimelsp/LSP-json#185]
Am I supposed to create the complete own schema file? From what file as a base? I see `"allowComments": true` setting for sublime-config files but, it is unclear to me how to use it for other files.

**Comment by rchl** [comment]
Basic schema can look something like https://github.com/sublimelsp/LSP-json/blob/master/schemas/vscode-base.json

You'd need to create it and assign it manually within the json file or globally through the https://github.com/sublimelsp/LSP-json?tab=readme-ov-file#custom-schemas package settings.
