### ISSUE TITLE
Remove support for sublime-settings

### ISSUE THREAD

**Issue by AmjadHD** [sublimelsp/LSP-json#2]
I don't think that treating `.sublime-settings` files as `jsonc` makes much sence, since:
1. trailing commas are allowed and somewhat encouraged in `.sublime-settings`  but not in `jsonc`, which produces errors everywhere.
2. hover doesn't work since there are no scheme files for `.sublime-settings`.
3. document symbols are arguably unneeded, since sublime's goto symbols is good enough.

**Comment by predragnikolic** [comment]
You are absolutely right. Sublime settings file is not the same as jsonc. I will remove it.

**Comment by jfcherng** [comment]
Just a FYI. LSP will not emit errors on trailing commas in `jsonc` if using `"vscode-json-languageserver": "=1.2.1"`.

**Comment by predragnikolic** [comment]
I think we should add back support for Sublime setting files, now that the jsonc server won't report errors for trailing commas. 🙂

**Comment by AmjadHD** [comment]
@predragnikolic, FWIW This server is not using [vscode-json-languageserver](https://github.com/vscode-langservers/vscode-json-languageserver) directly, but rather the less maintained [vscode-json-languageserver-bin](https://github.com/vscode-langservers/vscode-json-languageserver-bin), I Think you should switch.

**Comment by jfcherng** [comment]
@AmjadHD https://github.com/sublimelsp/LSP-json/pull/4

**Comment by rchl** [comment]
Resolved on master.
