### ISSUE TITLE
Add support for user defined json schema definitions

### ISSUE THREAD

**Issue by deathaxe** [sublimelsp/LSP-json#34]
The following line causes all user defined schema definitions contained in a LSP-json.sublime-settings file to be overwritten.

https://github.com/sublimelsp/LSP-json/blob/033b2eddf83692b4cbf52f9554a605fed5519de0/plugin.py#L32

Should we change it to something like ...

```python
configuration['settings'].setdefault('json', {})['schemas'].extend(cls._default_schemas)
```

Note: Maybe dedupping is needed.

**Comment by rchl** [comment]
I've been tinkering with this before and have some unfinished local changes. Will look into it now.
