### ISSUE TITLE
Directly use the server from its source repo

### ISSUE THREAD

**Issue by jfcherng** [sublimelsp/LSP-json#36]
Currently, we fetch the server code from [this NPM package](https://www.npmjs.com/package/vscode-json-languageserver). I propose that we should directly build the server codes from https://github.com/vscode-langservers/vscode-json-languageserver because

- It gives us the ability to get any specific build of the server.
- The one on NPM has not been updated for 5 months.
- The maintainer of https://github.com/vscode-langservers/vscode-json-languageserver is not a collaborator of the NPM package. Asking those collaborators to update is annoying and they may be unresponsive.
- We have already done that in [LSP-css](https://github.com/sublimelsp/LSP-css/blob/master/language-server/compile-language-server.sh) and [LSP-html](https://github.com/sublimelsp/LSP-html/blob/master/language-server/compile-language-server.sh) so this should be an easy move.

**Comment by predragnikolic** [comment]
Just tried the #37 PR, working on my side also(Linux, st build 4077) 

The downside is that we won't receive automatic PR from `dependabot` when they release a new version to npm. 
We need to check for updates manually, which is what I would like to avoid. 
As you said, this npm package wasn't updated for 5 months and we do the strategy you introduced with #37 for LSP-html and LSP-css, so I am fine with merging #37.
 
The one thing I tried looking was opening an issue at the repo to ask them if they could make a release, but there is no issues tab. I would more like if the maintainers of the json langauge server released a new version on npm. :)

@jfcherng what would you like more? Full control but manually(periodically) do an update of getting the latest master (the responsibility is on us), or using dependabot and relaying on automatic PR(the responsibility is on the maintainer of the NPM package) but we may end up with situations like this where the package wasn't updated for a 5months.

**Comment by jfcherng** [comment]
Personally I don't like a long release cycle like this. Basing on the history, they may have a new release if they don't forget it.

![image](https://user-images.githubusercontent.com/6594915/87238192-1486aa00-c432-11ea-97da-5dfafd6cd909.png)

---

As for `LSP-css` and `LSP-html`, there is no NPM package so we have no choice except to build them by ourselves.

**Comment by rchl** [comment]
If we can't rely on NPM package being updated regularly then I think we have no other option than updating manually from source.
