### ISSUE TITLE
Syntax-specific settings don't have a correct schema

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP-json#44]
When you open syntax-specific settings (e.g. `Preferences: Settings - Syntax Specific` in the command palette), then these should also inherit all of the keys of the global Preferences.sublime-settings. As well as any packages that add more settings to Preferences.sublime-settings via #43

**Comment by rchl** [comment]
We have to address https://github.com/sublimelsp/LSP/issues/997 to be able to start LSP-json for sublime-project files.

**Comment by rwols** [comment]
While that’s true, it’s not really applicable to the problem. For example I have my sublime projects in the root of my workspace folders, but I ignore them with my local gitignore settings (or local SVN ignore dir).

**Comment by rchl** [comment]
OK, in that case it's not an issue. For me I have them managed by Project Manager so all are in `Packages/User/Projects/` and opening those using `Edit Project` doesn't start the server. I could drag whole folder onto ST of course.

We should at least allow workspace-less servers to start inside unrelated projects. I guess we should have a ClientConfig key for that.

**Comment by rwols** [comment]
Regarding the attaching of langservers outside of the project, it would be best if we do it regardless of a setting first, and add some sort of Boolean setting only if people complain about too many diagnostic squiggles (which I predict won’t happen)

**Comment by rchl** [comment]
I'm not sure if diagnostics would be the only issue. Eslint likes to show full-view errors (through `window/logMessage` or something) in case it can't find configuration files also.

**Comment by rchl** [comment]
Was fixed both for projects and syntax-specific settings.
