### ISSUE TITLE
project settings only support "editor" settings

### ISSUE THREAD

**Issue by AmjadHD** [sublimelsp/LSP-json#47]
https://github.com/sublimelsp/LSP-json/commit/59bd467d6aea879b1208c4e579bcd0de2c9f685f added a reference to the preferences schema in the project settings, which doesn't restrict the settings to those of the "editor" category.
![image](https://user-images.githubusercontent.com/33235928/91508726-99416080-e8d8-11ea-9817-9e215a0f4402.png)

**Comment by rchl** [comment]
Yes but it's not explicitly marked which are editor settings so who should maintain the list and make sure that it's correct?

**Comment by AmjadHD** [comment]
It is possible to include only editor settings through schemas (in the autocompletions), but not disallow other ui and application behaviour settings.
This is a restriction in draft7.

**Comment by rchl** [comment]
Not having explicit restrictions and only providing completions for editor settings would be fine IMO.
We are not likely to achieve the full strictness anyways, as that would require that *every* package provides a schema.

But still, the main issue IMO is knowing which ones are "editor" settings and maintaining that list.

Also, it's not just "Editor" settings if we consider third-party packages which can also contribute to those settings.
