### ISSUE TITLE
schema file patterns with whitespace

### ISSUE THREAD

**Issue by deathaxe** [sublimelsp/LSP-json#51]
Just noticed the file patterns for jsonschema extensions must not contain whitespace. Space needs to be escaped via `%20` instead. It's quite logical from the `uri` perspective, but might not be too obvious.

The question is: Is it intended behavior or may some sort of translation be added, which escapes spaces and possibly other characters?

```
{
    "contributions": {
        "settings": [
            {
                "file_patterns": [
                    "A%20File%20Icon.sublime-settings"
                ],
                "schema": {
```

**Comment by rchl** [comment]
I think it makes sense to simplify that.

It's matched against file paths that per LSP spec are URIs. I'll use `urllib.parse.quote` to encode file patterns. That could encode too much. I had to explicitly exclude `*` from encoding and I might have missed some other characters that should not be encoded.

Server handles that pattern by [escaping and converting to RegExp](https://github.com/microsoft/vscode-json-languageservice/blob/76f4b43d475f67fd58c6bd2eaea1b0cd01826f84/src/utils/strings.ts#L34-L36) so it's quite a custom hanlding.

**Comment by deathaxe** [comment]
Thanks!
