### ISSUE TITLE
How about supporting json-with-comments?

### ISSUE THREAD

**Issue by f5lee** [sublimelsp/LSP-json#74]
Many config files that have json schemas allow comments, the vscode json language server has an allowComments option, and vscode recognizes the .jsonc suffix as allowing comments.

This is distinct from other variants like json5 or hjson, because it's about just comments. There's generally wide support for comments in json config, less so for the other modifications of json. And there are some programs out there that implement their own "ignore comments in json config" parsing.

**Comment by rchl** [comment]
Do you specifically have a `.jsonc` extension in mind or something more?

Many of the schemas supplied by this server are using `allowComments` option already. For example the schemas for ST preferences.

It's just a matter of adding extra association and basic schema for `.jsonc` if that's all that this is about.

**Comment by rchl** [comment]
Also, you can easily do it yourself with `userSchemas` option: https://github.com/sublimelsp/LSP-json/blob/e947a3b116ba97099683282217fc651adf84dfdd/LSP-json.sublime-settings#L37-L46

But if would like this behavior to be present by default then it can be added to the package probably. In which case consider creating a PR.

**Comment by f5lee** [comment]
1. I think supporting a .jsonc file extension would be useful. I have an eslintrc that extends a common config with a .jsonc suffix.

2. Many json config files like eslintrc allow comments, but the canonical schema doesn't have allowComments. json schema doesn't have a simple way of saying "use this schema that inherits from that schema but with these changes".

**Comment by rchl** [comment]
Supporting `.jsonc` would be easy.

Supporting number 2 not so much. VSCode uses either "JSON" or "JSON with comments" syntax and it has those associations stored internally (or provided by schemas). We don't have those associations defined anywhere. I guess we could be slowly building such a database but then we would also have to figure out how to send a `jsonc` language ID for those files, rather than `json`. That might require a change in the LSP package but should be doable. So the tricky part is compiling a database of "file pattern => language ID" mappings.

**Comment by f5lee** [comment]
How about something simple like a global option to turn on allowComments for all json? Currently, schema validation for something like eslintrc is great except the "comments are not allowed" complaints are very noisy.

It's very unlikely that someone will accidentally write a comment in a json file, and any such errors are going to be quickly error when the file is read.

**Comment by rchl** [comment]
That shouldn't be that hard but it appears that it become quite harder recently due to some changes in LSP. I'll get back to you on that :)

Are you on ST3 or ST4?

**Comment by rchl** [comment]
@f5lee what specific files did you had mind for this?

This will be handled with a whitelist that the user can also edit if he wants.

So far I have those files/extensions in the list:
```
			".babelrc",
			".eslintrc",
			".eslintrc.json",
			".hintrc",
			".jsfmtrc",
			".jshintrc",
			".jsonc",
			".swcrc",
			"/.ember-cli",
			"/.vscode/*.json",
			"/jsconfig-*.json",
			"/jsconfig.*.json",
			"/jsconfig.json",
			"/tsconfig-*.json",
			"/tsconfig.*.json",
			"/tsconfig.json",
```

**Comment by f5lee** [comment]
ST3 at the moment. That seems fine to me.

Also should add "babel.config.json".

Thanks!

**Comment by rchl** [comment]
For ST3 you can just set `"languageId": "jsonc"` like so:

```js
	"languages": [
		{
			"languageId": "jsonc",
			"scopes": ["source.json"],
			// ...
         }
      ]
````

This will apply to all json files of course.
