### ISSUE TITLE
JSON formatting

### ISSUE THREAD

**Issue by Klaster1** [sublimelsp/LSP-json#76]
The readme states:
>Uses VSCode JSON Language Server to provide validation, _**formatting**_ and other features for JSON files. See linked repository for more information.

From this, I understand the "formatting" means "document formatting", which I'd like to do. Assuming "VSCode JSON Language Server" is the "linked repository" mentioned in the quote, I spent some time looking through its issues and readme, but could not figure out how to enable JSON formatting or to trigger the command. Does "LSP-json" really supports this? If true, the readme does not help much with setup or asks too much of a user.

**Comment by jfcherng** [comment]
![image](https://user-images.githubusercontent.com/6594915/101239113-f3479280-371f-11eb-8340-1bc6711453d3.png)

**Comment by rwols** [comment]
Perhaps you're using ST3. In that case, you can only format the selection.

**Comment by Klaster1** [comment]
@rwols this was the issue, thanks for help! I'd add this to readme.
