### ISSUE TITLE
Unknown Source contributing incorrect supported values for sublime-settings

### ISSUE THREAD

**Issue by alanCarpenter-Trov** [sublimelsp/LSP-json#93]
Trying to modify the Sublime `file_tab_style` is met with 

`warning Value is not accepted. Valid values: "rounded", "squared", "angled". ​unknown-source:1`

![sublime settings issue](https://i.imgur.com/ZRjY5ef.png)

When the choice of "Squared" is selected the tabs section breaks entirely. This is because the actual accepted value is "square"

**Comment by rwols** [comment]
Thanks for the report! @predragnikolic fixed this in #94, should show up on package control soon.
